export const EXPIRE_IN_REFRESH_SECONDS = 60;
export const EXPIRE_IN_REFRESH_MINUTES = 60;
export const EXPIRE_IN_REFRESH_HOURS = 24;
export const EXPIRE_IN_REFRESH_DAYS = 7;
export const EXPIRE_IN_ACCESS_SECONDS = 60;
export const EXPIRE_IN_ACCESS_MINUTES = 15;
export const EXPIRE_IN_TIME_ACCESS = EXPIRE_IN_ACCESS_SECONDS * EXPIRE_IN_ACCESS_MINUTES;
export const EXPIRE_IN_TIME_REFRESH =
	EXPIRE_IN_REFRESH_SECONDS *
	EXPIRE_IN_REFRESH_MINUTES *
	EXPIRE_IN_REFRESH_HOURS *
	EXPIRE_IN_REFRESH_DAYS;
